main:
    log_file: /home/proxima/Desktop/collectr/log/collectr.log
    log_level: debug
    log_directory: /home/proxima/Desktop/collectr/log
    agent_cache_directory: /home/proxima/Desktop/collectr/cache
    language: en
    interval: 15
    agent_subprocesses: 10
    listen_address: 127.0.0.1
    bind_port: 5000
    api_server_name: 127.0.0.1
    api_server_port: 6000
    api_server_https: False
    api_server_uri: /infoset/api/v1
    